# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux

r:
  - oldrel
  - release
  - devel

env:
  global:
    - LINTR_COMMENT_BOT=false


warnings_are_errors: false # set to true: This option forces all WARNINGS from R CMD check
  # to become build failures (default true). This is especially helpful when preparing
  # your package for submission to CRAN

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

cache: packages

after_success:
  # code coverage
  - Rscript -e 'if (requireNamespace("covr")) covr::codecov()'

